# Generated by Django 2.2.3 on 2019-07-31 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('image', models.FileField(default='', upload_to='gallery_image')),
            ],
        ),
    ]
