# Generated by Django 2.2.3 on 2019-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech'), ('Intern', 'Intern'), ('Research Scholar', 'Research Scholar')], max_length=100),
        ),
    ]
