# Generated by Django 2.2.3 on 2019-07-31 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsite', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('photo', models.FileField(default='', upload_to='gallery_image')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
