# Generated by Django 2.2.3 on 2019-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsite', '0002_auto_20190802_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dblp',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='google_scholar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
