# Generated by Django 2.2.3 on 2019-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsite', '0003_auto_20190802_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('On Going', 'On Going')], default='', max_length=100),
        ),
    ]
